### ISSUE TITLE
Support import bbs common with file protocol

### ISSUE THREAD

**Issue by yanivyehu** [deweb-io/vidibate#1] opened 2022-12-20 12:43 UTC

**Comment by israeldeweb** [comment] 2022-12-22 20:02
This seems to work for me just fine. What's the problem?

**Comment by israeldeweb** [comment] 2022-12-22 20:03
Duplicate of https://github.com/deweb-io/bbs-common/issues/1

**Comment by israeldeweb** [comment] 2022-12-27 11:28
We always fetch from node modules when we are server side, but client side should attempt to get the package from the server before defaulting to the CDN.

**Closed as completed** 2023-01-12 16:15 UTC
Labels: enhancement
